name: Bazel on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [opt, dbg]
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4.1.3
    - uses: bazel-contrib/setup-bazel@0.8.3
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true

    - name: Build
      run: bazel build -c ${{ matrix.build_type }}

    - name: Test
      run: bazel test -c ${{ matrix.build_type }}
